name: '.NET Deploy'

on:
  workflow_call:
    inputs:
      job_name:
        type: string
        required: true
      environment:
        type: string
        required: true
      app_name:
        type: string
        required: true
      api_name:
        type: string
        required: true
      www_location:
        type: string
        required: true
    secrets:
      gh_token:
        required: true
      aswa_token:
        required: true

jobs:
  deploy:
    name: ${{ inputs.job_name }}

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "APP_LOCATION=${{ github.workspace }}/${{ inputs.app_name }}/published" >> $GITHUB_ENV
        echo "API_LOCATION=${{ github.workspace }}/${{ inputs.api_name }}/published" >> $GITHUB_ENV
        echo "OUTPUT_LOCATION=${{ inputs.www_location }}" >> $GITHUB_ENV

    # - name: Check environment variables
    #   shell: bash
    #   run: |
    #     echo $APP_LOCATION
    #     echo $API_LOCATION
    #     echo $OUTPUT_LOCATION

    - name: Download WebApp artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.app_name }}_app
        path: ${{ env.APP_LOCATION }}

    - name: Download ApiApp artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.api_name }}_app
        path: ${{ env.API_LOCATION }}

    - name: Check WebApp artifact
      shell: bash
      run: |
        cd ${{ env.APP_LOCATION }}
        ls -al

    - name: Check ApiApp artifact
      shell: bash
      run: |
        cd ${{ env.API_LOCATION }}
        ls -al

    - name: Deploy Static Web App 
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.aswa_token }}
        repo_token: ${{ secrets.gh_token }} # Used for Github integrations (i.e. PR comments)
        action: upload
        skip_app_build: true
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: $APP_LOCATION # App source code path
        api_location: $API_LOCATION # Api source code path - optional
        output_location: $OUTPUT_LOCATION # Built app content directory - optional
        ###### End of Repository/Build Configurations ######
