name: 'PR Close'

on:
  pull_request:
    types:
    - closed
    branches:
    - main
    paths:
    - 'src/**'
    - 'test/**'

jobs:
  close_pull_request_job:
    name: Close Pull Request

    runs-on: ubuntu-latest

    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          action: "close"
